### ISSUE TITLE
Re-estimate new release

### ISSUE THREAD

**Issue by brandondrew** [trailblazer/trailblazer-finder#18]
> NEW README AND RELEASE COMING NEXT WEEK

It's been several weeks now since this was posted.  It may be good to post a new estimate that is in the future.

**Comment by obiyuta** [comment]
> > NEW README AND RELEASE COMING NEXT WEEK
> 
> It's been several weeks now since this was posted. It may be good to post a new estimate that is in the future.

I agree.

**Comment by seuros** [comment]
released.
